apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-dev
  labels:
    app: resume-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-dev
  template:
    metadata:
      labels:
        app: resume-dev
    spec:
      containers:
      - name: resume
        image: ghcr.io/steasdal/resume-responsive:sha-758aab3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: ghcrcredential

---

apiVersion: v1
kind: Service
metadata:
  name: resume-dev
  labels:
    app: resume-dev
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: resume-dev

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-dev-ingress
spec:
  rules:
    - host: resume-dev.teasdale.dev
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: resume-dev
                port:
                  number: 80
