name: CI

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      packages: write

    steps:

      # Checkout out this repo and ALSO the steasdal/gitops repo
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the ghcr container repository
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: What is the tag?
        run: echo "Tag - ${{ steps.get_version.outputs.VERSION }}"

      # We're going to update the version placeholder in index.html with the git sha.  This'll
      # never actually be committed to the git repo - it'll exist only in the docker container.
      - name: update the version
        run: sed -i -r "s|version:.*|version:\ ${{ steps.get_version.outputs.VERSION }}</a>|" content/index.html

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: "ghcr.io/steasdal/resume-responsive:${{ steps.get_version.outputs.VERSION }}"

      # Using a sed command with a "|" delimeter instead of the usual slash
      # due to the fact that the replacement value itself has slashes in it.
      - name: Update deploy/prod/deploy.yaml
        run: sed -i -r "s|image:.*|image:\ ghcr.io/steasdal/resume-responsive:${{ steps.get_version.outputs.VERSION }}|" deploy/prod/deploy.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Sam Teasdale
          author_email: samuel.teasdale@gmail.com
          message: 'Committing changes to deploy.yaml'
          add: 'deploy/prod/*'
